### ISSUE TITLE
[1pt] Choose assets - group task

### ISSUE THREAD

**Issue by nicupop729** [nicupop729/JavaScript-Capstone#19]
Choose images, text, icons, fonts.

**Comment by micheaol** [comment]
## -List of Icons ##
likes icon :  https://fontawesome.com/v5.15/icons/thumbs-up?style=regular
comments icon:  https://fontawesome.com/v5.15/icons/comment?style=regular


## -List of fonts :
- font-family: 'Roboto', sans-serif;
- font-family: 'Lato', sans-serif;

## -List of images for logo ##
![bg_pizza](https://user-images.githubusercontent.com/10332499/141868546-42737345-26fa-4147-b633-ec0ce4010a1f.jpg)
![create_pizza](https://user-images.githubusercontent.com/10332499/141868556-be6091c8-c3fc-4440-92ed-0cea5e1bf5f7.jpg)
![pizza_logo](https://user-images.githubusercontent.com/10332499/141868565-67df0bcb-1f33-4eb9-97d0-db54817551ae.png)

**Comment by nicupop729** [comment]
**That's good, really good research.**

Improvements approved.

Please, meanwhile, think about a name for our site. Something connected with pizza
