### ISSUE TITLE
Peer-to-Peer Code Review 18-11-2021

### ISSUE THREAD

**Issue by Qoosim** [nicupop729/JavaScript-Capstone#35]
## Good Job :100: 
You guys have really put in a lot of works into this project.
You followed JavaScript good practices and your code is clean.

### Observation
- Update your readme file
- In a function called itemCounter, if what is in my mind is quite the same as what your intention is, I will say it is better to return counter instead of returning value.length. Since the content of the counter is the value.length.

Once again, good job so far :+1:

**Comment by nicupop729** [comment]
resolved
