### ISSUE TITLE
Peer to peer code review 11/18/2021

### ISSUE THREAD

**Issue by AlexRS90** [nicupop729/JavaScript-Capstone#36]
# Hi team, this is an amazing job so far, congratulations 🚀  💯 
## Highlights:
- Your code works as expected 👨‍💻 
- Your code is clean, easy to follow and read 📖 
- Use async functions

## Suggestions:
- It'd be nice if you put the functions to call the API in another module, in order to make your code even more readable. Here are the functions ⬇️ 
https://github.com/nicupop729/JavaScript-Capstone/blob/ae6457653e28910b3f463bc23c8763f47991e32e/src/display-comments.js#L60-L81
- Inside the the pop up, you have some links with orange color, I think you can improve the constrast with the background changing the color, in order to make your code accesible for all people. 😃   🟠   🟢 

### Keep it up! 🚀  🚀

**Comment by nicupop729** [comment]
resolved
